#!/usr/bin/env python3
# This is just a quick test script I used to evaluate some hand-picked cases.
# Ronin does not get them all correct.  With the default frequency table and
# parameter values, it fails 11 cases.

import os
import sys

try:
    sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
    sys.path.append(os.path.join(os.path.dirname(__file__), "../.."))
except:
    sys.path.append("..")
    sys.path.append("../..")

from spiral import ronin

success_cases = {
    'JavaTokenMarker': ['Java', 'Token', 'Marker'],
    'ullMax': ['ull', 'Max'],
    'cmdextdir': ['cmd', 'ext', 'dir'],
    'jrender': ['j', 'render'],
    'mythread': ['my', 'thread'],
    'JRApiWriter': ['JR', 'Api', 'Writer'],
    'ijException': ['ij', 'Exception'],
    'pixellate': ['pixellate'],
    'hostloader': ['host', 'loader'],
    'tagcount': ['tag', 'count'],
    'calleeNode': ['callee', 'Node'],
    'WMLTimerElementImpl': ['WML', 'Timer', 'Element', 'Impl'],
    'PRINTHOOD': ['PRINT', 'HOOD'],
    'patternstok': ['patterns', 'tok'],
    'needsibm': ['needs', 'ibm'],
    'rthandler': ['rt', 'handler'],
    'finalizeLength': ['finalize', 'Length'],
    'iwebnavigation': ['iweb', 'navigation'],
    'getint': ['get', 'int'],
    'getinteger': ['get', 'integer'],
    'isinstance': ['is', 'instance'],
    'nwritten': ['n', 'written'],
    'vframe': ['v', 'frame'],
    'xmldoc': ['xml', 'doc'],
    'somevar': ['some', 'var'],
    'usage_getdata': ['usage', 'get', 'data'],
    'GPSmodule': ['GPS', 'module'],
    'bigTHING': ['big', 'THING'],
    'ABCFooBar': ['ABC', 'Foo', 'Bar'],
    'getMAX': ['get', 'MAX'],
    'SqlList': ['Sql', 'List'],
    'ASTVisitor': ['AST', 'Visitor'],
    'isnumber': ['is', 'number'],
    'threshold': ['threshold'],
    'initdb': ['init', 'db'],
    'terraindata': ['terrain', 'data'],
    'trigname': ['trig', 'name'],
    'undirected': ['undirected'],
    'usemap': ['use', 'map'],
    'updatecpu': ['update', 'cpu'],
    'textnode': ['text', 'node'],
    'connectpath': ['connect', 'path'],
    'mpegts': ['mpegts'],
    'iskeyword': ['is', 'keyword'],
    'mixmonitor': ['mix', 'monitor'],
    'isbetterfile': ['is', 'better', 'file'],
    'm_pk2len': ['m', 'pk', '2', 'len'],
    'pcmret': ['pcm', 'ret'],
    'autocommit': ['autocommit'],
    'httpexceptions': ['http', 'exceptions'],
    'sampfmt': ['samp', 'fmt'],
    'readcmd': ['read', 'cmd'],
    'nonnegativedecimaltype': ['nonnegative', 'decimal', 'type'],
    'filesaveas': ['file', 'save', 'as'],
    'filesave': ['file', 'save'],
    'wickedweather': ['wicked', 'weather'],
    'liquidweather': ['liquid', 'weather'],
    'gocompact': ['go', 'compact'],
    'slimprojector': ['slim', 'projector'],
    'farsidebag' : ['far', 'side', 'bag'],
    'urlparser': ['url', 'parser'],
    'altscore': ['alt', 'score'],
    'rescale': ['rescale'],
    'csize': ['c', 'size'],
    'xmax': ['x', 'max'],
    'cdplayer': ['cd', 'player'],
    'cdimage': ['cd', 'image'],
    'xmin': ['x', 'min'],
    'iptool': ['ip', 'tool'],
    'getxy': ['get', 'xy'],
    'TRAinfo': ['TRA', 'info'],
    'initVtbl': ['init', 'V', 'tbl'],
}

failure_cases = {
   'driveourtrucks': ['drive', 'our', 'trucks'],
   'uval': ['u', 'val'],
   'hisip': ['his', 'ip'],
   'lunch_defendj': ['lunch', 'defend', 'j'],
   'sandcx': ['sandcx'],
   'numberoferrorgroups': ['number', 'of', 'error', 'groups'],
   'thisisatest': ['this', 'is', 'a', 'test'],
   'singlexmin': ['single', 'x', 'min'],
   'icause': ['i', 'cause'],
   'argv': ['arg', 'v'],
}

successes = 0
failures = 0

for identifier, expected in sorted(success_cases.items()):
    result = ronin.split(identifier)
    if result != expected:
        failures +=1
        print('unexpected failure: {} => {}'.format(identifier, result))
    else:
        successes +=1

for identifier, expected in sorted(failure_cases.items()):
    result = ronin.split(identifier)
    if result != expected:
        successes +=1
    else:
        print('unexpected success: {} => {}'.format(identifier, result))
        failures +=1

print('{} surprises, {} as expected'.format(failures, successes))
